# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      shell: bash
      run: |
        mod tidy
        go mod vendor
        go build -mod=vendor ./cmd/shox

    - name: Create tarball
      id: package
      shell: bash
      run: |
        tar cfz shox.tgz shox 
        # Let subsequent steps know where to find the compressed package
        echo "PKG_PATH=shox.tgz" >> $GITHUB_OUTPUT

    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: shox.tgz
        path: shox.tgz

    - name: Publish package
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ steps.package.outputs.PKG_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
